"""Add audio_signal_analysis column to Recording model

Revision ID: 45915b1d039a
Revises: a53daca59f9c
Create Date: 2024-09-24 10:23:43.805090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45915b1d039a'
down_revision = 'a53daca59f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_signal_analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('audio_signal_analysis')

    # ### end Alembic commands ###
