"""Added s3_presigned_url

Revision ID: a53daca59f9c
Revises: c309d0e523ef
Create Date: 2024-09-23 13:13:09.027298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53daca59f9c'
down_revision = 'c309d0e523ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_presigned_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('s3_presigned_url')

    # ### end Alembic commands ###
